// echo_core: echonote's cross-platform C audio core, called from Dart via
// dart:ffi (bindings generated by ffigen from this header).
//
// Conventions for every function here:
// - Audio is mono PCM16 (int16_t). Nothing depends on the sample rate;
//   echonote uses 16 kHz.
// - Functions never allocate (except ec_vad_create) and never keep a pointer
//   they were given; the caller owns every buffer.
// - n <= 0 means "no samples": no memory is read or written.
// - Stateless functions are safe on any thread. An ec_vad is not
//   thread-safe: use each one from a single isolate.
// - Every function is short and never calls back into Dart, so Dart binds
//   them as leaf calls.

#ifndef ECHO_CORE_H
#define ECHO_CORE_H

#include <stdint.h>

#if _WIN32
#define EC_EXPORT __declspec(dllexport)
#else
#define EC_EXPORT __attribute__((visibility("default")))
#endif

#ifdef __cplusplus
extern "C" {
#endif

// Converts PCM16 to float in [-1, 1): out[i] = in[i] / 32768.
// Same formula whisper_ggml uses before decoding.
EC_EXPORT void ec_pcm16_to_float(const int16_t *in, float *out, int32_t n);

// Root-mean-square level of `in`, normalized so 32768 is 1.0.
// Returns 0 when n <= 0.
EC_EXPORT float ec_rms_pcm16(const int16_t *in, int32_t n);

// Splits `n` samples into `buckets` equal runs and writes each run's peak
// absolute value (0..1) to `out`. Writes min(buckets, n) values and returns
// that count; returns 0 (writing nothing) when n <= 0 or buckets <= 0.
EC_EXPORT int32_t ec_waveform_downsample(const int16_t *in, int32_t n, float *out,
                                         int32_t buckets);

// Energy-gate voice activity detector. Same algorithm and defaults as the
// gate in whisper_ggml's live stream (whisper_flutter_plus.cpp): an adaptive
// noise floor that falls fast and rises slowly, and a chunk is voiced when
// its RMS reaches max(voice_ratio * noise_floor, rms_min).
typedef struct ec_vad_config {
  float initial_noise_floor;  // 0.005
  float rms_min;              // 0.0015
  float voice_ratio;          // 2.5
  float noise_floor_cap;      // 0.01
  float fall_rate;            // 0.5
  float rise_rate;            // 0.0005
} ec_vad_config;

typedef struct ec_vad ec_vad;

// The defaults listed above.
EC_EXPORT ec_vad_config ec_vad_default_config(void);

// Returns NULL if allocation fails.
EC_EXPORT ec_vad *ec_vad_create(ec_vad_config config);

// Updates the noise floor with this chunk and returns 1 if it is voiced,
// 0 otherwise. n <= 0 returns 0 and leaves the state unchanged.
EC_EXPORT int32_t ec_vad_process(ec_vad *vad, const int16_t *in, int32_t n);

// Puts the noise floor back to its initial value.
EC_EXPORT void ec_vad_reset(ec_vad *vad);

// Frees `vad`. NULL is a no-op.
EC_EXPORT void ec_vad_destroy(ec_vad *vad);

#ifdef __cplusplus
}
#endif

#endif  // ECHO_CORE_H
