// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:echo_core/echo_core_bindings_generated.dart')
library;

import 'dart:ffi' as ffi;
import '' as self;

/// Converts PCM16 to float in [-1, 1): out[i] = in[i] / 32768.
/// Same formula whisper_ggml uses before decoding.
@ffi.Native<
  ffi.Void Function(ffi.Pointer<ffi.Int16>, ffi.Pointer<ffi.Float>, ffi.Int32)
>(isLeaf: true)
external void ec_pcm16_to_float(
  ffi.Pointer<ffi.Int16> in$,
  ffi.Pointer<ffi.Float> out,
  int n,
);

/// Root-mean-square level of `in`, normalized so 32768 is 1.0.
/// Returns 0 when n <= 0.
@ffi.Native<ffi.Float Function(ffi.Pointer<ffi.Int16>, ffi.Int32)>(isLeaf: true)
external double ec_rms_pcm16(ffi.Pointer<ffi.Int16> in$, int n);

/// Splits `n` samples into `buckets` equal runs and writes each run's peak
/// absolute value (0..1) to `out`. Writes min(buckets, n) values and returns
/// that count; returns 0 (writing nothing) when n <= 0 or buckets <= 0.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<ffi.Int16>,
    ffi.Int32,
    ffi.Pointer<ffi.Float>,
    ffi.Int32,
  )
>(isLeaf: true)
external int ec_waveform_downsample(
  ffi.Pointer<ffi.Int16> in$,
  int n,
  ffi.Pointer<ffi.Float> out,
  int buckets,
);

/// The defaults listed above.
@ffi.Native<ec_vad_config Function()>(isLeaf: true)
external ec_vad_config ec_vad_default_config();

/// Returns NULL if allocation fails.
@ffi.Native<ffi.Pointer<ec_vad> Function(ec_vad_config)>(isLeaf: true)
external ffi.Pointer<ec_vad> ec_vad_create(ec_vad_config config);

/// Updates the noise floor with this chunk and returns 1 if it is voiced,
/// 0 otherwise. n <= 0 returns 0 and leaves the state unchanged.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<ec_vad>, ffi.Pointer<ffi.Int16>, ffi.Int32)
>(isLeaf: true)
external int ec_vad_process(
  ffi.Pointer<ec_vad> vad,
  ffi.Pointer<ffi.Int16> in$,
  int n,
);

/// Puts the noise floor back to its initial value.
@ffi.Native<ffi.Void Function(ffi.Pointer<ec_vad>)>(isLeaf: true)
external void ec_vad_reset(ffi.Pointer<ec_vad> vad);

/// Frees `vad`. NULL is a no-op.
@ffi.Native<ffi.Void Function(ffi.Pointer<ec_vad>)>(isLeaf: true)
external void ec_vad_destroy(ffi.Pointer<ec_vad> vad);

const addresses = _SymbolAddresses();

class _SymbolAddresses {
  const _SymbolAddresses();
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ec_vad>)>>
  get ec_vad_destroy => ffi.Native.addressOf(self.ec_vad_destroy);
}

/// Energy-gate voice activity detector. Same algorithm and defaults as the
/// gate in whisper_ggml's live stream (whisper_flutter_plus.cpp): an adaptive
/// noise floor that falls fast and rises slowly, and a chunk is voiced when
/// its RMS reaches max(voice_ratio * noise_floor, rms_min).
final class ec_vad_config extends ffi.Struct {
  /// 0.005
  @ffi.Float()
  external double initial_noise_floor;

  /// 0.0015
  @ffi.Float()
  external double rms_min;

  /// 2.5
  @ffi.Float()
  external double voice_ratio;

  /// 0.01
  @ffi.Float()
  external double noise_floor_cap;

  /// 0.5
  @ffi.Float()
  external double fall_rate;

  /// 0.0005
  @ffi.Float()
  external double rise_rate;
}

final class ec_vad extends ffi.Opaque {}
